Gymnasium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
    path('', include('accounts.urls'))
]

# for handling profile photos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('add/', login_required(views.add_member), name='add_member'),
    path('search/', login_required(views.search_member), name='search_member'),
    path('view/', login_required(views.view_member), name='view_member'),
    path('delete/<int:id>/', login_required(views.delete_member), name='delete_member'),
    path('update/<int:id>/', login_required(views.update_member), name='update_member'),
    path('', login_required(views.members), name='members'),
]

members/models.py
import datetime

from django import forms
from django.db import models
from django.forms import ModelForm

SUBSCRIPTION_TYPE_CHOICES = (
    ("gym", "Gym"),
    # ("cross_fit", "Cross Fit"),
    # ("gym_and_cross_fit", "Gym + Cross Fit"),
    ("pt", "Personal Training"),
)

SUBSCRIPTION_PERIOD_CHOICES = (
    ("0.25", "Quarter Month"),
    ("0.5", "Half Month"),
    ("1", "1 Month"),
    ("2", "2 Months"),
    ("3", "3 Months"),
    ("4", "4 Months"),
    ("5", "5 Months"),
    ("6", "6 Months"),
    ("7", "7 Months"),
    ("8", "8 Months"),
    ("9", "9 Months"),
    ("10", "10 Months"),
    ("11", "11 Months"),
    ("12", "12 Months"),
)

FEE_STATUS = (
    ("paid", "Paid"),
    ("pending", "Pending"),
)

STATUS = (
    (0, "Start"),
    (1, "Stop"),
)

BATCH = (
    ("morning", "Morning"),
    ("evening", "Evening"),
)


class Member(models.Model):
    member_id = models.AutoField(primary_key=True)
    unique_member_id = models.CharField(("MEMBER's GYM ID"), max_length=50)
    first_name = models.CharField(("First Name"), max_length=50)
    last_name = models.CharField(("Last Name"), max_length=50)
    mobile_number = models.CharField(("Mobile Number"), max_length=10, unique=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=300, blank=True)
    medical_history = models.CharField(
        ("Medical History"), max_length=300, blank=True, default="None"
    )
    admitted_on = models.DateField(auto_now_add=True)
    registration_date = models.DateField(("Registration Date"), default="dd/mm/yyyy")
    start_date = models.DateField(("Start Date"), default="dd/mm/yyyy")
    registration_upto = models.DateField()
    dob = models.DateField(default="dd/mm/yyyy")
    subscription_type = models.CharField(
        ("Subscription Type"),
        max_length=30,
        choices=SUBSCRIPTION_TYPE_CHOICES,
        default=SUBSCRIPTION_TYPE_CHOICES[0][0],
    )
    subscription_period = models.CharField(
        ("Subscription Period"),
        max_length=30,
        choices=SUBSCRIPTION_PERIOD_CHOICES,
        default=SUBSCRIPTION_PERIOD_CHOICES[2][0],
    )
    amount = models.CharField(max_length=30)
    fee_status = models.CharField(
        ("Fee Status"), max_length=30, choices=FEE_STATUS, default=FEE_STATUS[0][0]
    )
    batch = models.CharField(max_length=30, choices=BATCH, default=BATCH[0][0])
    photo = models.FileField(upload_to="photos/", blank=True)
    notification = models.IntegerField(default=2, blank=True)
    stop = models.IntegerField(
        ("Status"), choices=STATUS, default=STATUS[0][0], blank=True
    )

    def __str__(self):
        return self.first_name + " " + self.last_name


class AddMemberForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddMemberForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].error_messages = {
            "required": "Please enter first name"
        }
        self.fields["last_name"].error_messages = {"required": "Please enter last name"}

    class Meta:
        model = Member
        # fields = ['first_name', 'last_name', 'mobile_number', 'email', 'address', 'subscription_type', 'subscription_period', 'amount']
        fields = "__all__"
        exclude = ["registration_upto"]
        widgets = {
            "registration_date": forms.DateInput(
                attrs={"class": "datepicker form-control", "type": "date"}
            ),
            "start_date": forms.DateInput(
                attrs={"class": "datepicker form-control", "type": "date"}
            ),
            "address": forms.Textarea(attrs={"cols": 80, "rows": 3}),
            "medical_history": forms.Textarea(attrs={"cols": 80, "rows": 3}),
            "dob": forms.DateInput(
                attrs={"class": "datepicker form-control", "type": "date"}
            ),
            "photo": forms.FileInput(attrs={"accept": "image/*;capture=camera"}),
        }

    def clean_mobile_number(self, *args, **kwargs):
        mobile_number = self.cleaned_data.get("mobile_number")
        if not mobile_number.isdigit():
            raise forms.ValidationError("Mobile number should be a number")
        if Member.objects.filter(mobile_number=mobile_number).exists():
            raise forms.ValidationError(
                "This mobile number has already been registered."
            )
        else:
            if len(str(mobile_number)) == 10:
                return mobile_number
            else:
                raise forms.ValidationError("Mobile number should be 10 digits long.")
        return mobile_number

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        if not amount.isdigit():
            raise forms.ValidationError("Amount should be a number")
        return amount

    def clean(self):
        cleaned_data = super().clean()
        dob = cleaned_data.get("dob")
        first_name = cleaned_data.get("first_name").capitalize()
        last_name = cleaned_data.get("last_name").capitalize()
        queryset = Member.objects.filter(
            first_name=first_name, last_name=last_name, dob=dob
        ).count()
        if queryset > 0:
            raise forms.ValidationError("This member already exists!")


class SearchForm(forms.Form):
    search = forms.CharField(label="Search Member", max_length=100, required=False)

    def clean_search(self, *args, **kwargs):
        search = self.cleaned_data.get("search")
        if search == "":
            raise forms.ValidationError("Please enter a name in search box")
        return search


class UpdateMemberGymForm(forms.Form):
    registration_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "datepicker        form-control", "type": "date"}
        ),
    )
    start_date = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "datepicker        form-control", "type": "date"}
        ),
    )
    registration_upto = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "datepicker form-control", "type": "date"}
        ),
    )
    subscription_type = forms.ChoiceField(choices=SUBSCRIPTION_TYPE_CHOICES)
    subscription_period = forms.ChoiceField(choices=SUBSCRIPTION_PERIOD_CHOICES)
    fee_status = forms.ChoiceField(choices=FEE_STATUS)
    amount = forms.CharField()
    batch = forms.ChoiceField(choices=BATCH)
    # subscription_upto = datetime.strptime(str(registration_upto), "%d/%m/%Y")
    # today = datetime.now()
    stop = forms.ChoiceField(label="Status", choices=STATUS)
    # if subscription_upto.date() < today.date():
    #     stop = "stop"

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        if not amount.isdigit():
            raise forms.ValidationError("Amount should be a number")
        return amount


class UpdateMemberInfoForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    unique_member_id = forms.CharField(max_length=50)
    mobile_number = forms.CharField(max_length=10)
    email = forms.CharField(max_length=50)
    address = forms.CharField(max_length=300)
    photo = forms.FileField(label="Update Photo", required=False)
    dob = forms.DateField(
        widget=forms.DateInput(
            attrs={"class": "datepicker        form-control", "type": "date"}
        ),
    )

members/forms.py
from django import forms

class AddMemberForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    mobile_number = forms.IntegerField()
     = forms.EmailField()

members/templates/add_member.html
{% extends 'base.html' %}
{% load tags %}

{% block title %}
Members
{% endblock %}

{% block content %}
<style type="text/css">
  .req {
    text-decoration: none;
    color: red;
  }
</style>
<div class="container" style="margin-top: 3%; margin-bottom: 3%">
  {% if add_success %}
  <!-- Modal -->
  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="addTaskTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="container text-center">
            <div class="alert alert-dark" style="margin-bottom: 0">
              <p style="margin-bottom: 0">{{ add_success }}</p>
              <form method="POST" action="{% url 'update_member' member.member_id %}">
                {% csrf_token %}
                <div>Want to print user data?</div>
                <input type="submit" class="btn btn-success btn-sm" name="export" value="Yes" />
                <input type="submit" class="btn btn-danger btn-sm" name="no" value="No" />
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if form.errors %}
  {% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endif %}
  <form method="POST" action="{% url 'add_member' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-3">
        <img src="/media/default.jpg" class="img-fluid">
        <div class="form-group" style="padding-top: 10px;">
          <label for="photo">Upload Photo:</label>
          {{ form.photo | add_css:"form-control" }}
        </div>
        <div class="form-group">
          <label for="photo">DOB:<span class="req"> *</span></label>
          {{ form.dob }}
        </div>
        <button type="submit" class="btn btn-dark btn-block">Add</button>
      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="first_name">{{ form.first_name.label }}<span class="req"> *</span></label>
            {{ form.first_name | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="last_name">{{ form.last_name.label }}<span class="req"> *</span></label>
            {{ form.last_name | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="unique_member_id">{{ form.unique_member_id.label }}<span class="req"> *</span></label>
            {{ form.unique_member_id | add_css:"form-control" }}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="mobile_number">{{ form.mobile_number.label }}<span class="req"> *</span></label>
            {{ form.mobile_number | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="email">{{ form.email.label }}</label>
            {{ form.email | add_css:"form-control" }}
          </div>
        </div>
        <div class="row">
          <div class="col form-group">
            <label for="address">{{ form.address.label }}</label>
            {{ form.address | add_css:"form-control" }}
          </div>
          <div class="col form-group">
            <label for="address">{{ form.medical_history.label }}</label>
            {{ form.medical_history | add_css:"form-control" }}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="subscription_type">{{ form.subscription_type.label }}<span class="req"> *</span></label>
            {{ form.subscription_type | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="subscription_period">{{ form.subscription_period.label }}<span class="req"> *</span></label>
            {{ form.subscription_period | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="amount">{{ form.amount.label }}<span class="req"> *</span></label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text">₹</span>
              </div>
              {{ form.amount | add_css:"form-control" }}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="fee_status">{{ form.fee_status.label }}<span class="req"> *</span></label>
            {{ form.fee_status | add_css:"form-control" }}
          </div>
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="registration_date">{{ form.registration_date.label }}<span class="req"> *</span></label>
            {{ form.registration_date }}
          </div>
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="start_date">{{ form.start_date.label }}<span class="req"> *</span></label>
            {{ form.start_date }}
          </div>
          <div class="form-group col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <label for="batch">{{ form.batch.label }}<span class="req"> *</span></label>
            {{ form.batch | add_css:"form-control" }}
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block javascript %}
<script>
  $(window).on('load', function () {
    $('#modal').modal('show');
  });
</script>
{% endblock %}

members/templates/update_member.html
{% load tags %}
<div class="container" style="margin-top: 3%">
    {% if deleted %}
        <div class="alert alert-success">
            {{ deleted }}
        </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-lg-6 col-md-6 col-sm-12 col-xs-12 offset-md-3 text-center">
                <label for="search">{{ search_form.search.label }}</label>
                {{ search_form.search | add_css:"form-control" }}
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
            <button type="submit" id="submit" class="btn btn-primary">Search</button>
        </div>
    </form>
    <div id="ajax_result" style="margin-top: 2%;"></div>
</div>

members/templates/view_member.html
{% extends 'base.html' %}
{% load tags %}
{% load static %}

{% block title %}
Members
{% endblock %}

{% block content %}

<div class="container" style="margin-top: 3%">
  {% if deleted %}
  <div class="alert alert-success">
    {{ deleted }}
  </div>
  {% endif %}
  {% if search_form.errors %}
  {% for field in search_form %}
  {% for error in field.errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endfor %}
  {% for error in search_form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endif %}
  <form method="POST" action="{% url 'search_member' %}">
    {% csrf_token %}
    <div class="row">
      <div class="form-group col"></div>
      <div class="form-group col">
        <label for="search">{{ search_form.search.label }}</label>
        {{ search_form.search | add_css:"form-control" }}
      </div>
      <div class="{% if not result %} col {% endif %}">
        <button type="submit" id="submit" class="btn btn-danger" style="margin-top: 30px;">Search</button>
      </div>
      {% if result %}
      <div class="col">
        <button type="submit" id="clear" name="clear" class="btn btn-dark" style="margin-top: 30px;">Clear</button>
      </div>
      {% endif %}
    </div>
  </form>
  <!-- <div id="ajax_result" style="margin-top: 2%;"></div> -->
</div>

{% if result %}
<div class="container" style="margin-top: 3%">
  <table class="table table-striped table-bordered">
    <thead class="text-center thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Memeber's Gym ID</th>
        <!-- <th scope="col">Photo</th> -->
        <th scope="col">Registration Date</th>
        <th scope="col">Start Date</th>
        <th scope="col">Subscription Upto</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">Subscription Period</th>
        <th scope="col">Fees</th>
        <th scope="col">Delete User</th>
      </tr>
    </thead>
    <tbody class="text-center">
      {% for member in result %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="/members/update/{{ member.member_id }}">{{ member.first_name }} {{ member.last_name }}</a></td>
        <td>{{ member.unique_member_id }}</td>
        <td>{{ member.registration_date }}</td>
        <td>{{ member.start_date }}</td>
        <td>{{ member.registration_upto }}</td>
        <td>{{ member.mobile_number }}</td>
        <td>{{ member.subscription_period }} Months</td>
        <td>
          {% if member.fee_status == 'paid' %}
          <span class="icon-checkmark" style="color: green"></span>
          {% else %}
          <span class="icon-cross" style="color: red"></span>
          {% endif %}
        </td>
        <td><a href="/members/delete/{{ member.member_id }}/"><button class="btn btn-danger"
              onclick="return confirm('Are you sure you want to delete this? This will permanently delete the record!')">Delete</button></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#all" role="tab" aria-controls="home"
      aria-selected="true">All</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="home-tab" data-toggle="tab" href="#morning" role="tab" aria-controls="home"
      aria-selected="true">Morning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#evening" role="tab" aria-controls="profile"
      aria-selected="false">Evening</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#stopped" role="tab" aria-controls="stopped"
      aria-selected="false">Expired</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="home-tab">
    <div class="container" style="margin-top: 3%">
      <table class="table table-striped table-bordered">
        <thead class="text-center thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Member's Gym ID</th>
            <!-- <th scope="col">Photo</th> -->
            <th scope="col">Registration Date</th>
            <th scope="col">Start Date</th>
            <th scope="col">Subscription Upto</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Subscription Period</th>
            <th scope="col">Fees</th>
          </tr>
        </thead>
        <tbody class="text-center">
          {% for member in all %}
          <tr>
            <th scope="row">{{ all.start_index|add:forloop.counter0 }}</th>
            <td><a href="/members/update/{{ member.member_id }}">{{ member.first_name }} {{ member.last_name }}</a></td>
            <td>{{ member.unique_member_id }}</td>
            <td>{{ member.registration_date }}</td>
            <td>{{ member.start_date }}</td>
            <td>{{ member.registration_upto }}</td>
            <td>{{ member.mobile_number }}</td>
            <td>{{ member.subscription_period }} Months</td>
            <td>
              {% if member.fee_status == 'paid' %}
              <span class="icon-checkmark" style="color: green"></span>
              {% else %}
              <span class="icon-cross" style="color: red"></span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if all.has_other_pages %}
      <ul class="pagination">
        {% if all.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ all.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
        {% endif %}
        {% for i in all.paginator.page_range %}
        {% if all.number == i %}
        <li class="page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if all.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ all.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
        {% endif %}
      </ul>
      {% endif %}
    </div>
  </div>

  <div class="tab-pane fade show" id="morning" role="tabpanel" aria-labelledby="home-tab">
    <div class="container" style="margin-top: 3%">
      <table class="table table-striped table-bordered">
        <thead class="text-center thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Member's Gym ID</th>
            <!-- <th scope="col">Photo</th> -->
            <th scope="col">Registration Date</th>
            <th scope="col">Start Date</th>
            <th scope="col">Subscription Upto</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Subscription Period</th>
            <th scope="col">Fees</th>
          </tr>
        </thead>
        <tbody class="text-center">
          {% for member in morning %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="/members/update/{{ member.member_id }}">{{ member.first_name }} {{ member.last_name }}</a></td>
            <td>{{ member.unique_member_id }}</td>
            <td>{{ member.registration_date }}</td>
            <td>{{ member.start_date }}</td>
            <td>{{ member.registration_upto }}</td>
            <td>{{ member.mobile_number }}</td>
            <td>{{ member.subscription_period }} Months</td>
            <td>
              {% if member.fee_status == 'paid' %}
              <span class="icon-checkmark" style="color: green"></span>
              {% else %}
              <span class="icon-cross" style="color: red"></span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="tab-pane fade show" id="evening" role="evening" aria-labelledby="profile-tab">
    <div class="container" style="margin-top: 3%">
      <table class="table table-striped table-bordered">
        <thead class="text-center thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Member's Gym ID</th>
            <!-- <th scope="col">Photo</th> -->
            <th scope="col">Registration Date</th>
            <th scope="col">Start Date</th>
            <th scope="col">Subscription Upto</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Subscription Period</th>
            <th scope="col">Fees</th>
          </tr>
        </thead>
        <tbody class="text-center">
          {% for member in evening %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="/members/update/{{ member.member_id }}">{{ member.first_name }} {{ member.last_name }}</a></td>
            <td>{{ member.unique_member_id }}</td>
            <td>{{ member.registration_date }}</td>
            <td>{{ member.start_date }}</td>
            <td>{{ member.registration_upto }}</td>
            <td>{{ member.mobile_number }}</td>
            <td>{{ member.subscription_period }} Months</td>
            <td>
              {% if member.fee_status == 'paid' %}
              <span class="icon-checkmark" style="color: green"></span>
              {% else %}
              <span class="icon-cross" style="color: red"></span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="tab-pane fade show" id="stopped" role="stopped" aria-labelledby="profile-tab">
    <div class="container" style="margin-top: 3%">
      <table class="table table-striped table-bordered">
        <thead class="text-center thead-dark">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Member's Gym ID</th>
            <!-- <th scope="col">Photo</th> -->
            <th scope="col">Registration Date</th>
            <th scope="col">Start Date</th>
            <th scope="col">Subscription Upto</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Subscription Period</th>
            <th scope="col">Fees</th>
          </tr>
        </thead>
        <tbody class="text-center">
          {% for member in stopped %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="/members/update/{{ member.member_id }}">{{ member.first_name }} {{ member.last_name }}</a></td>
            <td>{{ member.unique_member_id }}</td>
            <td>{{ member.registration_date }}</td>
            <td>{{ member.start_date }}</td>
            <td>{{ member.registration_upto }}</td>
            <td>{{ member.mobile_number }}</td>
            <td>{{ member.subscription_period }} Months</td>
            <td>
              {% if member.fee_status == 'paid' %}
              <span class="icon-checkmark" style="color: green"></span>
              {% else %}
              <span class="icon-cross" style="color: red"></span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

{% block javascript %}
<!-- <script>
    $("#submit").click(function (event) {
      event.preventDefault();
      var search = $("#id_search").val();

      $.ajax({
        type: 'POST',
        url: '{% url "search_member" %}',
        data: {
          'search': search,
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        dataType: 'json',
        success: function (data) {
          var search = JSON.parse(data.search);
          var appended_html = '<table class="table table-bordered"><thead class="text-center"><tr><th>ID</th><th>Name</th><th>Edit</th><th>Delete</th></tr></thead><tbody class="text-center">';
          for (var i=0; i<search.length; i++) {
              // now each search[i] has an object within it
              var obj = search[i];  // obj is an alias for each object in the array
              //Now you can access each key-value pair like this
              var fields = obj.fields;
              var member_id = obj.pk;
              var first_name = fields.first_name;
              var last_name = fields.last_name;
              appended_html += '<tr><td>' + (i + 1) + '</td><td>' + first_name + ' ' + last_name + '</td><td><a href="/members/update/' + member_id + '/"><button class="btn btn-success">Edit</button><td><a href="/members/delete/' + member_id + '/"><button class="btn btn-danger">Delete</button></a></td></tr>';
          }
          // alert(appended_html);
          // alert('Yes');
          appended_html += '</tbody></table>';
          $('#ajax_result').html(appended_html);
        }
      });
      // return false;
    });
  </script> -->
<script type="text/javascript">
  $(document).ready(function () {
    $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
      localStorage.setItem('activeTab', $(e.target).attr('href'));
    });
    var activeTab = localStorage.getItem('activeTab');
    if (activeTab) {
      $('#myTab a[href="' + activeTab + '"]').tab('show');
      //localStorage.removeItem('activeTab');
    }
  });
</script>
{% endblock %}